services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_goStocker
    restart: always
    ports:
      - "8888:80"
    environment:
      # PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      # PGADMIN_DEFAULT_PASSWORD: strong-password
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

volumes:
  local_pgdata:
  pgadmin_data: